name = "momfood-cloud-kitchen"
compatibility_date = "2024-01-01"
pages_build_output_dir = "dist"

# Environment variables (set these in Cloudflare Pages dashboard)  
[env.production.vars]
NODE_ENV = "production"

[env.preview.vars]
NODE_ENV = "preview"