name = "momfood-cloud-kitchen"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[build]
command = "npm run build"
cwd = "."

[[pages]]
# Cloudflare Pages configuration
project_name = "momfood-cloud-kitchen"

[pages.build]
command = "npm run build"
destination_dir = "dist"

# Environment variables (set these in Cloudflare Pages dashboard)
[env.production.vars]
NODE_ENV = "production"

[env.preview.vars]
NODE_ENV = "preview"