# Cloudflare Pages Configuration

# Build settings
build = {
  command = "npm run build"
  publish = "dist"
}

# Environment variables
[env.production]
NODE_VERSION = "18"

[env.preview]
NODE_VERSION = "18"

# Compatibility settings
compatibility_date = "2024-08-14"
compatibility_flags = ["nodejs_compat"]

# Custom headers for SPA routing
[[headers]]
for = "/*"
[headers.values]
X-Frame-Options = "DENY"
X-Content-Type-Options = "nosniff"
Referrer-Policy = "strict-origin-when-cross-origin"

# SPA fallback for client-side routing
[[redirects]]
from = "/*"
to = "/index.html"
status = 200
force = false